### ISSUE TITLE
Can't locate path: </home/vagrant/services/vendor/nickurt/laravel-openprovider/src/../src/Resources/Lang

### ISSUE THREAD

**Issue by ghermans** [nickurt/laravel-openprovider#1]
I receive the current error when i try to execute the publish command
```
Can't locate path: </home/vagrant/services/vendor/nickurt/laravel-openprovider/src/../src/Resources/Lang>
```

**Comment by nickurt** [comment]
fixed, but keep in the mind that this package is far from complete and still WIP ...

**Comment by ghermans** [comment]
No problem @nickurt  still it is nice to see that someone is working on a package for Openprovider.
Also i would like to ask if it is possible to update the readme with a usage example?

**Comment by nickurt** [comment]
It follows the basic functions already, like the way [OpenProvider](https://doc.openprovider.eu/Main_Page) posted it in the API-docs

In short, its like this
```php
\OpenProvider::customers()->searchCustomer(array $params)
\OpenProvider::customers()->retrieveCustomer(array $params)

\OpenProvider::domains()->searchDomain(array $params)
\OpenProvider::domains()->retreiveDomain(array $params)

\OpenProvider::extensions()->searchExtension(array $params)
\OpenProvider::extensions()->retrieveExtension(array $params)

\OpenProvider::financials()->searchTransactionReseller(array $params)

\OpenProvider::licenses()->searchProductLicense(array $params)
\OpenProvider::licenses()->retrieveProductLicense(array $params)

\OpenProvider::resellers()->retrieveReseller()

\OpenProvider::ssl()->searchProductSslCert()
\OpenProvider::ssl()->retrieveProductSslCert(array $params)
```

It's also possible to dependency inject OpenProvider directly in your controller-functions
```php
public function getIndex(OpenProvider $openProvider)
{
    $customers = $openProvider->customers()->searchCustomer(array $params)

    //
}
```

If you want to use other connection-information, (provided in `config/openprovider.php`), you can use the connection function. If you don't use a connection function, it will automatically use the default one.
```php
\OpenProvider::connection('openprovider-ppe')->searchCustomer(array $params)
```
If you need functions that are not available yet with the plugin, I'm happy too see a pull-request (just follow the pattern as above, described in the OpenProvider-docs)

I will update the readme with this information asap.

**Comment by nickurt** [comment]
Just wanted to let you know I pushed a big update today ...

https://github.com/nickurt/laravel-openprovider/commit/f3c4fe890dedaec4ec4111c4bbe17519cae57651

**Comment by ghermans** [comment]
Thanks for the update, i will test it tonight.
