### ISSUE TITLE
Use of guzzle provider in laravel

### ISSUE THREAD

**Issue by matthijs** [nickurt/laravel-openprovider#4]
At this point we are using your package to communicate to OpenProvider. This works as intended. We are also writing unittests to make sure that adjustments to our codebase do not have any side effect. To be able to write those tests we need to mock the responses from OpenProvider but that doesn't seem possible with your package at this moment.

Could you make use of a guzzle provider so that we can mock the responses for guzzle?

We use https://packagist.org/packages/kozz/laravel-guzzle-provider as provider and that way we can write unittests by adding responses to mock handler from guzzle. Now we can test our application to check if it correctly acts on the responses from OpenProvider.

Example on how we use it:
```php
use GuzzleHttp\Client;
use GuzzleHttp\Handler\MockHandler;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Psr7\Response;

class OpenProviderTest inherits TestCase {
  public function setupMockGuzzle() {
    $this->mockHandler = new MockHandler();
    $handler = HandlerStack::create($this->mockHandler);
    $client = new Client(['handler' => $handler]);
    $this->app->instance('guzzle', $client);
  }

  public function testOpenprovider() {
    $this->setupMockGuzzle();

    $this->mockHandler->append(new Response(200, [], 'body of the request'));

    // Now call the tests for openprovider
  }
}
```

Instead of (https://github.com/nickurt/laravel-openprovider/blob/master/src/HttpClient/HttpClient.php#L27)
```php
$this->client = new \GuzzleHttp\Client();
```
use:
```php
$this->client = \Kozz\Laravel\Facades\Guzzle::getFacadeRoot();
```

I am aware that OpenProvider has a testing environment but this testing environment has limits which make it impossible to use with unittests. Unittests are executed very often which would exceed the limits of the test environment pretty fast.

**Comment by nickurt** [comment]
Hi matthijs,

Thank you for your kind words and issue-report, I think it's more cleaner that we gonna implement that we can set a custom HttpClient/Client, so you can use your mock directly in the HttpClient/construct (src/HttpClient/HttpClient.php).

I will look into this later this week.

**Comment by nickurt** [comment]
Hi matthijs,

You can attach your mocks now via the `setClient()` function in this package, e.g:

```php
$client = new Client([
    'handler' => HandlerStack::create($mockHandler = new MockHandler())
]);

$mockHandler->append(new Response(200, [], '<?xml version="1.0" encoding="UTF-8"?><openXML><reply><code>0</code><desc></desc><data><results><array><item><id>1337</id></item></array></results></data></reply></openXML>'));

$openProvider = app('OpenProvider');
$openProvider->getHttpClient()->setClient($client);

$this->assertArraySubset([
    'reply' => [
        'code' => '0',
        'desc' => [],
        'data' => [
            'results' => [
                'array' => [
                    'item' => [
                        'id' => '1337'
                    ]
                ]
            ]
        ]
    ]
], $openProvider->customers()->searchCustomer([
    'limit' => 1
]));
````

**Comment by matthijs** [comment]
Thank you very much, I will test it in our code.

**Comment by matthijs** [comment]
I can confirm this works. Thank you!

**Comment by nickurt** [comment]
Good to hear, good luck :)
